#> metadata #
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

title: ILGPU - A Modern GPU Compiler for .Net Programs
email: ilgpucompiler@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A modern, lightweight & fast GPU compiler for high-performance .Net programs.

social_links:
  github: https://github.com/m4rs-mt/ILGPU
  discord: https://discord.com/invite/X6RBCff
gh_contribute_base: 'master/docs/'
#< metadata #


#> permalinks and default layouts #
permalink: pretty # remove .html extension from permalinks

collections:
  docs:
    output: true # telling Jekyll to render _docs/ and generate pages
    permalink: /:collection/:title/

defaults: # adding default layouts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
#< permalinks and default layouts #


#> jekyll-relative-links #
relative_links:
  enabled: true
  collections: true # set to true for processing _docs/
  exclude:
    - DOCUMENTATION.md
#< jekyll-relative-links #


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

sass:
  style: compressed

exclude:
  - jekyll-theme-arsha.gemspec
  - DOCUMENTATION.md
  - README.md
  - LICENSE
